version: '4.0'

services:

  webapp:
    stdin_open: true
    tty: true
    working_dir: /home/phoenix-trello
    image: dockercontainervm/phoenix-trello:latest
    container_name: phoenix
    expose:
      - 4000
      - 5432
    ports:
      - "3000:4000"
      - "5432:5432"
    entrypoint: ./run-services-docker.sh
    environment:
      - PATH=/root/.kiex/elixirs/elixir-1.3.1/bin:/root/.kiex/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  chrome:
    image: selenium/standalone-chrome:3.141.59-dubnium
    shm_size: 2gb
    expose:
      - 4444
      - 7900
    ports:
      - "4444:4444"
      - "7900:7900"
    volumes:
      - /dev/shm:/dev/shm # Recommended for Chrome to avoid crashes
    depends_on:
      - webapp


