version: '4.0'

services:

  webapp:
    stdin_open: true
    tty: true
    working_dir: /var/www/html/pagekit
    image: dockercontainervm/pagekit:latest
    container_name: pagekit
    expose:
      - 80
      - 3306
    ports:
      - "3000:80"
      - "3306:3306"
    entrypoint: ./run-services-docker.sh
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  chrome:
    image: selenium/standalone-chrome:3.141.59-dubnium
    shm_size: 2gb
    expose:
      - 4444
      - 7900
    ports:
      - "4444:4444"
      - "7900:7900"
    volumes:
      - /dev/shm:/dev/shm # Recommended for Chrome to avoid crashes
    depends_on:
      - webapp


